### ISSUE TITLE
Load data seg bgr

### ISSUE THREAD

**Issue by ahyunSeo** [xiaomengyc/SG-One#6]
Hello,

I'm looking around your code.
I've noticed that the mydataset seems to use bgr image from cv2.imread.
But you uses rgb mean and rgb pretrained pytorch vgg models.
Is there anything I missed?
I'll very appreciate if you help this out.
https://github.com/xiaomengyc/SG-One/blob/master/utils/mydataset.py#L46

Regards,
Ahyun

**Comment by xiaomengyc** [comment]
Hi @ahyunSeo , 
Thanks for the carefulness. Actually, I did not really notice this issue. This configuration goes well in training classification networks. I think the statistic differences between RGB and BGR channels might be minor and the networks can adapt to these differences very well.
