### ISSUE TITLE
dat = datalayer.dequeue()

### ISSUE THREAD

**Issue by Saralyliu** [xiaomengyc/SG-One#7]
@xiaomengyc I trained the group_0_of_4 ,and achieved the path.tar files, then I used the test_frame_all.py to test, but I met with" 0%| | 0/1000 [00:00<?, ?it/s] "when debug at " for count in tqdm(range(1000)): dat = datalayer.dequeue()", it didn't work any more. Have you met with this and how can I deal with it ? and could you show some details about how to train and test the code?

**Comment by gaowq2017** [comment]
Hi@Saralyliu, I have the same problem, then how are you resolve it? Thank you! Best regard!
